services:
  - type: web
    name: recipelens
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src/RecipeLens.wsgi:application
    pythonVersion: 3.10.13
